% main_point.m
% Simple Directional Power Simulation Script

clear; clc;
addpath('lib');

% 1. USER INPUTS
N_az  = 180;
N_el  = 90;
irradiance = 1367;
config_list = {'a', 'b', 'c', 'd'};

% 2. OUTPUT DIRECTORY
out_dir = 'results';
if ~exist(out_dir, 'dir')
    mkdir(out_dir);
end

% 3. GENERATE SUMMARY TABLE FIRST
fprintf('\n=========================================================================================\n');
fprintf('%-10s | %-8s %-8s %-8s | %-24s | %-25s\n', 'Config', 'Min', 'Max', 'Avg (Real)', 'Avg (T=28C, EOL)', 'Avg (T=28C, BOL)');
fprintf('-----------------------------------------------------------------------------------------\n');
for idx = 1:numel(config_list)
    dvs_config = config_list{idx};
    
    % REAL (EOL + Temp Effects)
    [P_mean_real, P_min, P_max] = eval_power_custom(N_az, N_el, irradiance, dvs_config, false, false);
    
    % NO TEMP EFFECT (28 deg, EOL)
    [P_mean_notemp, ~, ~] = eval_power_custom(N_az, N_el, irradiance, dvs_config, true, false);
    
    % NO TEMP EFFECT + BOL (28 deg, BOL)
    [P_mean_notemp_bol, ~, ~] = eval_power_custom(N_az, N_el, irradiance, dvs_config, true, true);
    
    fprintf('%-10s | %-8.3f %-8.3f %-8.3f | %-24.3f | %-25.3f\n', ...
        upper(dvs_config), P_min, P_max, P_mean_real, P_mean_notemp, P_mean_notemp_bol);
end
fprintf('=========================================================================================\n\n');

% 4. RUN FULL SIMULATIONS & SAVE RESULTS
for idx = 1:numel(config_list)
    dvs_config = config_list{idx};
    config_tag = lower(dvs_config);

    % We evaluate the power generated by sampling the sun vector around a sphere
    [P_dir, T_cells, P_mean, cp, pc, phi_deg, theta_deg] = directional_power_sim(N_az, N_el, irradiance, dvs_config);
    face_labels = {pc.face};

    % Statistics
    P_flat = P_dir(:);
    fprintf('\n[dvs_sat_%s]\n', upper(config_tag));
    fprintf('Best-direction power    : %.4f W\n',  max(P_flat));
    fprintf('Mean over all directions: %.4f W\n',  P_mean);
    fprintf('Worst-direction power   : %.4f W\n',  min(P_flat));

    % Save per-configuration output
    result_file = sprintf('directional_results_dvs_sat_%s.mat', config_tag);
    save(fullfile(out_dir, result_file), ...
        'P_dir', 'T_cells', 'face_labels', 'P_flat', 'P_mean', ...
        'phi_deg', 'theta_deg', 'N_az', 'N_el', 'irradiance', 'cp', 'pc', 'dvs_config');

    fprintf('Saved to %s/%s\n', out_dir, result_file);
end

% Keep legacy filename for backward compatibility (last run config).
save(fullfile(out_dir, 'directional_results.mat'), ...
    'P_dir', 'T_cells', 'face_labels', 'P_flat', 'P_mean', ...
    'phi_deg', 'theta_deg', 'N_az', 'N_el', 'irradiance', 'cp', 'pc', 'dvs_config');
